language: python

python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "3.8"
  - "3.8-dev"
  - "3.9"
  - "3.9-dev"

install:
    - pip install poetry
    - poetry install

script:
    - poetry run nosetests --with-coverage --cover-package=pypdns tests/test.py
    - poetry run flake8 --ignore=E501,W503,E226,E252 .
    - poetry run mypy .

after_success:
    - poetry run codecov
    - poetry run coveralls
